config/routes.rb
Rails.application.routes.draw do
  # get "cart/show"
  # get "cart/add"
  # get "cart/update"
  # get "cart/remove"
  get "/cart", to: "cart#show", as: :cart
  post "/cart/add/:product_id", to: "cart#add", as: :add_to_cart
  patch "/cart/update/:product_id", to: "cart#update", as: :update_cart
  delete "/cart/remove/:product_id", to: "cart#remove", as: :remove_from_cart
  get "store/index"
  get "store/show"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :products
  resources :categories
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  # Change later - store index should be good for now.
  root "store#index"

  resources :products, only: [:index, :show], controller: "store"
  resources :orders, only: [:index, :new, :create, :show]
end

app/views/shared/_footer.html.erb
<footer>
  <p>&copy; <%= Time.current.year %> Ecommerce Store</p>
</footer>

app/views/shared/_navbar.html.erb
<nav>
    <div class="nav-container">
        <div class="nav-links">
            <%= link_to "Home", root_path %>
            <%= link_to "Products", root_path %> |
            <%= link_to "Categories", categories_path %> |

            <% if user_signed_in? %>
                <%= link_to "Cart", cart_path %>
                | <%= link_to "Orders", orders_path %>
                | <%= link_to "Admin", admin_root_path if current_user.admin? %>
                | Logged in as <%= current_user.email %>
                | <%= link_to "Profile", edit_user_registration_path %>
                | <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
            <% else %>
                | <%= link_to "Sign Up", new_user_registration_path %>
                | <%= link_to "Login", new_user_session_path %>
            <% end %>
        </div>
    </div>
</nav>